// Code generated by protoc-gen-go. DO NOT EDIT.
// source: actors-definitions.proto

package definitions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_actors_definitions_b54b7d02f4defbb7, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetAllUsersResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	Users                []*User  `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUsersResponse) Reset()         { *m = GetAllUsersResponse{} }
func (m *GetAllUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllUsersResponse) ProtoMessage()    {}
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_actors_definitions_b54b7d02f4defbb7, []int{1}
}
func (m *GetAllUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUsersResponse.Unmarshal(m, b)
}
func (m *GetAllUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUsersResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUsersResponse.Merge(dst, src)
}
func (m *GetAllUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllUsersResponse.Size(m)
}
func (m *GetAllUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUsersResponse proto.InternalMessageInfo

func (m *GetAllUsersResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetAllUsersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAllUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type CreateUserRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password" json:"Password,omitempty"`
	RoleID               int32    `protobuf:"varint,5,opt,name=RoleID" json:"RoleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_actors_definitions_b54b7d02f4defbb7, []int{2}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

type EditUserRequest struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password" json:"Password,omitempty"`
	RoleID               int32    `protobuf:"varint,6,opt,name=RoleID" json:"RoleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditUserRequest) Reset()         { *m = EditUserRequest{} }
func (m *EditUserRequest) String() string { return proto.CompactTextString(m) }
func (*EditUserRequest) ProtoMessage()    {}
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_actors_definitions_b54b7d02f4defbb7, []int{3}
}
func (m *EditUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserRequest.Unmarshal(m, b)
}
func (m *EditUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserRequest.Marshal(b, m, deterministic)
}
func (dst *EditUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserRequest.Merge(dst, src)
}
func (m *EditUserRequest) XXX_Size() int {
	return xxx_messageInfo_EditUserRequest.Size(m)
}
func (m *EditUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserRequest proto.InternalMessageInfo

func (m *EditUserRequest) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *EditUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *EditUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *EditUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EditUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EditUserRequest) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

type DeleteUserRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_actors_definitions_b54b7d02f4defbb7, []int{4}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(dst, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type AuthenticationParams struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationParams) Reset()         { *m = AuthenticationParams{} }
func (m *AuthenticationParams) String() string { return proto.CompactTextString(m) }
func (*AuthenticationParams) ProtoMessage()    {}
func (*AuthenticationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_actors_definitions_b54b7d02f4defbb7, []int{5}
}
func (m *AuthenticationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationParams.Unmarshal(m, b)
}
func (m *AuthenticationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationParams.Marshal(b, m, deterministic)
}
func (dst *AuthenticationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationParams.Merge(dst, src)
}
func (m *AuthenticationParams) XXX_Size() int {
	return xxx_messageInfo_AuthenticationParams.Size(m)
}
func (m *AuthenticationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationParams.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationParams proto.InternalMessageInfo

func (m *AuthenticationParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthenticationParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginParams struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginParams) Reset()         { *m = LoginParams{} }
func (m *LoginParams) String() string { return proto.CompactTextString(m) }
func (*LoginParams) ProtoMessage()    {}
func (*LoginParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_actors_definitions_b54b7d02f4defbb7, []int{6}
}
func (m *LoginParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginParams.Unmarshal(m, b)
}
func (m *LoginParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginParams.Marshal(b, m, deterministic)
}
func (dst *LoginParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginParams.Merge(dst, src)
}
func (m *LoginParams) XXX_Size() int {
	return xxx_messageInfo_LoginParams.Size(m)
}
func (m *LoginParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginParams.DiscardUnknown(m)
}

var xxx_messageInfo_LoginParams proto.InternalMessageInfo

func (m *LoginParams) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_actors_definitions_b54b7d02f4defbb7, []int{7}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "definitions.User")
	proto.RegisterType((*GetAllUsersResponse)(nil), "definitions.GetAllUsersResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "definitions.CreateUserRequest")
	proto.RegisterType((*EditUserRequest)(nil), "definitions.EditUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "definitions.DeleteUserRequest")
	proto.RegisterType((*AuthenticationParams)(nil), "definitions.AuthenticationParams")
	proto.RegisterType((*LoginParams)(nil), "definitions.LoginParams")
	proto.RegisterType((*LoginResponse)(nil), "definitions.LoginResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ActorsService service

type ActorsServiceClient interface {
	GetAllUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllUsersResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	EditUser(ctx context.Context, in *EditUserRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	Authenticate(ctx context.Context, in *AuthenticationParams, opts ...grpc.CallOption) (*GeneralResponse, error)
	ValidateToken(ctx context.Context, in *LoginParams, opts ...grpc.CallOption) (*LoginResponse, error)
}

type actorsServiceClient struct {
	cc *grpc.ClientConn
}

func NewActorsServiceClient(cc *grpc.ClientConn) ActorsServiceClient {
	return &actorsServiceClient{cc}
}

func (c *actorsServiceClient) GetAllUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllUsersResponse, error) {
	out := new(GetAllUsersResponse)
	err := grpc.Invoke(ctx, "/definitions.ActorsService/GetAllUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorsServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := grpc.Invoke(ctx, "/definitions.ActorsService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorsServiceClient) EditUser(ctx context.Context, in *EditUserRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := grpc.Invoke(ctx, "/definitions.ActorsService/EditUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorsServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := grpc.Invoke(ctx, "/definitions.ActorsService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorsServiceClient) Authenticate(ctx context.Context, in *AuthenticationParams, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := grpc.Invoke(ctx, "/definitions.ActorsService/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorsServiceClient) ValidateToken(ctx context.Context, in *LoginParams, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/definitions.ActorsService/ValidateToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ActorsService service

type ActorsServiceServer interface {
	GetAllUsers(context.Context, *Empty) (*GetAllUsersResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*GeneralResponse, error)
	EditUser(context.Context, *EditUserRequest) (*GeneralResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*GeneralResponse, error)
	Authenticate(context.Context, *AuthenticationParams) (*GeneralResponse, error)
	ValidateToken(context.Context, *LoginParams) (*LoginResponse, error)
}

func RegisterActorsServiceServer(s *grpc.Server, srv ActorsServiceServer) {
	s.RegisterService(&_ActorsService_serviceDesc, srv)
}

func _ActorsService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorsServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.ActorsService/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorsServiceServer).GetAllUsers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorsService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorsServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.ActorsService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorsServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorsService_EditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorsServiceServer).EditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.ActorsService/EditUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorsServiceServer).EditUser(ctx, req.(*EditUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorsService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorsServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.ActorsService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorsServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorsService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorsServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.ActorsService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorsServiceServer).Authenticate(ctx, req.(*AuthenticationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorsService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorsServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.ActorsService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorsServiceServer).ValidateToken(ctx, req.(*LoginParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActorsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "definitions.ActorsService",
	HandlerType: (*ActorsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUsers",
			Handler:    _ActorsService_GetAllUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _ActorsService_CreateUser_Handler,
		},
		{
			MethodName: "EditUser",
			Handler:    _ActorsService_EditUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _ActorsService_DeleteUser_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _ActorsService_Authenticate_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _ActorsService_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "actors-definitions.proto",
}

func init() {
	proto.RegisterFile("actors-definitions.proto", fileDescriptor_actors_definitions_b54b7d02f4defbb7)
}

var fileDescriptor_actors_definitions_b54b7d02f4defbb7 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0xcd, 0xd2, 0x75, 0xb7, 0x2b, 0xa8, 0x66, 0x9a, 0xac, 0x68, 0x42, 0x25, 0x3c, 0x50,
	0x84, 0xd8, 0xc3, 0xf8, 0x82, 0x8a, 0x96, 0xad, 0x52, 0x41, 0x23, 0x03, 0xde, 0x4d, 0x73, 0xd9,
	0x2c, 0xd2, 0x38, 0xd8, 0x2e, 0x88, 0x57, 0x7e, 0x82, 0x2f, 0xe0, 0x9f, 0xf8, 0x1c, 0x64, 0x27,
	0x69, 0xed, 0x76, 0xa3, 0x8f, 0x3c, 0x1e, 0xdf, 0x7b, 0x8f, 0xce, 0xbd, 0xe7, 0x24, 0x40, 0xd9,
	0x5c, 0x0b, 0xa9, 0x5e, 0x64, 0xf8, 0x99, 0x17, 0x5c, 0x73, 0x51, 0xa8, 0xd3, 0x52, 0x0a, 0x2d,
	0x48, 0xd7, 0x79, 0x8a, 0x0f, 0xd5, 0x0d, 0x93, 0x98, 0x55, 0xa5, 0xe4, 0x67, 0x00, 0x7b, 0x1f,
	0x14, 0x4a, 0x72, 0x1f, 0x5a, 0xd3, 0x31, 0x0d, 0x06, 0xc1, 0x30, 0x4a, 0x5b, 0xd3, 0x31, 0x39,
	0x81, 0x83, 0xd7, 0x5c, 0x2a, 0xfd, 0x96, 0x2d, 0x90, 0xb6, 0x06, 0xc1, 0xf0, 0x20, 0x5d, 0x3f,
	0x90, 0x18, 0x3a, 0x33, 0x56, 0x17, 0x43, 0x5b, 0x5c, 0x61, 0x72, 0x04, 0xd1, 0x64, 0xc1, 0x78,
	0x4e, 0xf7, 0x6c, 0xa1, 0x02, 0x66, 0xe2, 0x92, 0x29, 0xf5, 0x5d, 0xc8, 0x8c, 0x46, 0xd5, 0x44,
	0x83, 0x93, 0x12, 0x1e, 0x9e, 0xa3, 0x1e, 0xe5, 0xb9, 0x51, 0xa2, 0x52, 0x54, 0xa5, 0x28, 0x14,
	0x92, 0x63, 0x68, 0x5f, 0x69, 0xa6, 0x97, 0xaa, 0x96, 0x55, 0x23, 0x42, 0x61, 0xff, 0x0d, 0x2a,
	0xc5, 0xae, 0x1b, 0x61, 0x0d, 0x24, 0x4f, 0x21, 0x5a, 0x1a, 0x0a, 0x1a, 0x0e, 0xc2, 0x61, 0xf7,
	0xac, 0x7f, 0xea, 0xde, 0xc2, 0x90, 0xa7, 0x55, 0x3d, 0xf9, 0x15, 0x40, 0xff, 0x95, 0x44, 0xa6,
	0xd1, 0xbe, 0xe2, 0xd7, 0x25, 0x2a, 0xed, 0xef, 0x1c, 0xfc, 0x6b, 0xe7, 0xd6, 0x5d, 0x3b, 0x87,
	0x77, 0xed, 0xbc, 0xe7, 0xef, 0x6c, 0x96, 0x4b, 0x45, 0x8e, 0xd3, 0xb1, 0xbd, 0x46, 0x94, 0xd6,
	0x28, 0xf9, 0x1d, 0xc0, 0x83, 0x49, 0xc6, 0xb5, 0xab, 0xeb, 0x3f, 0x7a, 0xe3, 0xe8, 0x6c, 0x7b,
	0x3a, 0x9f, 0x43, 0x7f, 0x8c, 0x39, 0xfa, 0x07, 0x3c, 0x86, 0xb6, 0x81, 0x2b, 0xb1, 0x35, 0x4a,
	0x2e, 0xe0, 0x68, 0xb4, 0xd4, 0x37, 0x58, 0x68, 0x3e, 0x67, 0xc6, 0x8d, 0x4b, 0x26, 0xd9, 0x42,
	0x19, 0x39, 0x68, 0xe5, 0x54, 0xc7, 0xae, 0x80, 0x91, 0x53, 0x36, 0x72, 0xea, 0x43, 0x37, 0x38,
	0x79, 0x02, 0xdd, 0x99, 0xb8, 0xe6, 0x0e, 0x81, 0x16, 0x5f, 0xb0, 0x68, 0x08, 0x2c, 0x48, 0x9e,
	0x41, 0xcf, 0x36, 0xad, 0x92, 0x44, 0x61, 0x9f, 0xab, 0x8f, 0x2c, 0xe7, 0x99, 0x6d, 0xec, 0xa4,
	0x0d, 0x3c, 0xfb, 0x13, 0x42, 0x6f, 0x64, 0xbf, 0x9b, 0x2b, 0x94, 0xdf, 0xf8, 0x1c, 0xc9, 0x04,
	0xba, 0x4e, 0x18, 0x09, 0xf1, 0x32, 0x34, 0x59, 0x94, 0xfa, 0x47, 0x3c, 0xf0, 0xde, 0x6e, 0x89,
	0x6e, 0x72, 0x8f, 0xcc, 0x00, 0xd6, 0x01, 0x23, 0x8f, 0xbc, 0x89, 0xad, 0xe4, 0xc5, 0x27, 0x1b,
	0x8c, 0x05, 0x4a, 0x96, 0x3b, 0x6c, 0x17, 0xd0, 0x69, 0x42, 0x41, 0xfc, 0xde, 0x8d, 0xac, 0xec,
	0x64, 0x9a, 0x01, 0xac, 0x7d, 0xdb, 0xd0, 0xb5, 0x65, 0xe8, 0x4e, 0xb6, 0x77, 0x70, 0xe8, 0x18,
	0x8b, 0xe4, 0xb1, 0xd7, 0x7f, 0x9b, 0xe7, 0x3b, 0x29, 0xcf, 0xa1, 0x67, 0xad, 0x61, 0x1a, 0xdf,
	0x1b, 0x37, 0x09, 0xf5, 0x06, 0x1c, 0xf7, 0xe3, 0x78, 0xbb, 0xb2, 0x26, 0xfa, 0xd4, 0xb6, 0x7f,
	0xb8, 0x97, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xeb, 0xa9, 0xfc, 0x18, 0x05, 0x00, 0x00,
}
