// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roles-definitions.proto

package definitions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthorizationResponse struct {
	IsAuthorized         bool     `protobuf:"varint,1,opt,name=isAuthorized" json:"isAuthorized,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationResponse) Reset()         { *m = AuthorizationResponse{} }
func (m *AuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizationResponse) ProtoMessage()    {}
func (*AuthorizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_roles_definitions_c9ddbdc014be832d, []int{0}
}
func (m *AuthorizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationResponse.Unmarshal(m, b)
}
func (m *AuthorizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationResponse.Marshal(b, m, deterministic)
}
func (dst *AuthorizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationResponse.Merge(dst, src)
}
func (m *AuthorizationResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizationResponse.Size(m)
}
func (m *AuthorizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationResponse proto.InternalMessageInfo

func (m *AuthorizationResponse) GetIsAuthorized() bool {
	if m != nil {
		return m.IsAuthorized
	}
	return false
}

type AuthorizationParams struct {
	PermissionID         int32    `protobuf:"varint,1,opt,name=PermissionID" json:"PermissionID,omitempty"`
	ResourceName         string   `protobuf:"bytes,2,opt,name=ResourceName" json:"ResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationParams) Reset()         { *m = AuthorizationParams{} }
func (m *AuthorizationParams) String() string { return proto.CompactTextString(m) }
func (*AuthorizationParams) ProtoMessage()    {}
func (*AuthorizationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_roles_definitions_c9ddbdc014be832d, []int{1}
}
func (m *AuthorizationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationParams.Unmarshal(m, b)
}
func (m *AuthorizationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationParams.Marshal(b, m, deterministic)
}
func (dst *AuthorizationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationParams.Merge(dst, src)
}
func (m *AuthorizationParams) XXX_Size() int {
	return xxx_messageInfo_AuthorizationParams.Size(m)
}
func (m *AuthorizationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationParams.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationParams proto.InternalMessageInfo

func (m *AuthorizationParams) GetPermissionID() int32 {
	if m != nil {
		return m.PermissionID
	}
	return 0
}

func (m *AuthorizationParams) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthorizationResponse)(nil), "definitions.AuthorizationResponse")
	proto.RegisterType((*AuthorizationParams)(nil), "definitions.AuthorizationParams")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthorizationService service

type AuthorizationServiceClient interface {
	CanUser(ctx context.Context, in *AuthorizationParams, opts ...grpc.CallOption) (*AuthorizationResponse, error)
}

type authorizationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizationServiceClient(cc *grpc.ClientConn) AuthorizationServiceClient {
	return &authorizationServiceClient{cc}
}

func (c *authorizationServiceClient) CanUser(ctx context.Context, in *AuthorizationParams, opts ...grpc.CallOption) (*AuthorizationResponse, error) {
	out := new(AuthorizationResponse)
	err := grpc.Invoke(ctx, "/definitions.AuthorizationService/CanUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthorizationService service

type AuthorizationServiceServer interface {
	CanUser(context.Context, *AuthorizationParams) (*AuthorizationResponse, error)
}

func RegisterAuthorizationServiceServer(s *grpc.Server, srv AuthorizationServiceServer) {
	s.RegisterService(&_AuthorizationService_serviceDesc, srv)
}

func _AuthorizationService_CanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).CanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/definitions.AuthorizationService/CanUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).CanUser(ctx, req.(*AuthorizationParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthorizationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "definitions.AuthorizationService",
	HandlerType: (*AuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanUser",
			Handler:    _AuthorizationService_CanUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roles-definitions.proto",
}

func init() {
	proto.RegisterFile("roles-definitions.proto", fileDescriptor_roles_definitions_c9ddbdc014be832d)
}

var fileDescriptor_roles_definitions_c9ddbdc014be832d = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0xca, 0xcf, 0x49,
	0x2d, 0xd6, 0x4d, 0x49, 0x4d, 0xcb, 0xcc, 0xcb, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46, 0x12, 0x52, 0xb2, 0xe6, 0x12, 0x75, 0x2c, 0x2d, 0xc9, 0xc8,
	0x2f, 0xca, 0xac, 0x4a, 0x04, 0x89, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x29,
	0x71, 0xf1, 0x64, 0x16, 0xc3, 0xa4, 0x52, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x82, 0x50,
	0xc4, 0x94, 0x62, 0xb9, 0x84, 0x51, 0x34, 0x07, 0x24, 0x16, 0x25, 0xe6, 0x16, 0x83, 0xb4, 0x06,
	0xa4, 0x16, 0xe5, 0x66, 0x16, 0x17, 0x67, 0xe6, 0xe7, 0x79, 0xba, 0x80, 0xb5, 0xb2, 0x06, 0xa1,
	0x88, 0x81, 0xd4, 0x04, 0xa5, 0x16, 0xe7, 0x97, 0x16, 0x25, 0xa7, 0xfa, 0x25, 0xe6, 0xa6, 0x4a,
	0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0xa1, 0x88, 0x19, 0x65, 0x72, 0x89, 0xa0, 0x18, 0x1f, 0x9c,
	0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x14, 0xc8, 0xc5, 0xee, 0x9c, 0x98, 0x17, 0x5a, 0x9c, 0x5a,
	0x24, 0xa4, 0xa0, 0x87, 0xec, 0x3f, 0x2c, 0x8e, 0x91, 0x52, 0xc2, 0xad, 0x02, 0xe6, 0x57, 0x25,
	0x86, 0x24, 0x36, 0x70, 0xd0, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x27, 0x8d, 0x6d, 0x6d,
	0x35, 0x01, 0x00, 0x00,
}
